[package]
name = "swordfish"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"
description = "Cli tool for screen typing pre defined scripts"
readme = "README.md"
repository = "https://github.com/vim-zz/swordfish/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3", features = ["derive"] }
colored = "2"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
