[package]
name = "swordfish-rs"
version = "0.1.1"
edition = "2021"
license-file = "LICENSE"
description = "Cli tool for screen typing pre defined scripts"
readme = "README.md"
repository = "https://github.com/vim-zz/swordfish/"
exclude = [
    "tests/*",
]

[dependencies]
clap = { version = "3", features = ["derive"] }
colored = "2"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
